use_frameworks!

platform :ios, '9.0'

target 'HungryTools_Example' do
  pod 'HungryTools', :path => '../'
#  pod 'HungryTools'

  target 'HungryTools_Tests' do
    inherit! :search_paths

    
  end
end
